const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.ZAR_TEST_BROWSER});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));
 let files=[{id:'fixture-file',name:'Informe fixture.pdf',size:100,mime:'application/pdf',category:'documentos',owner_id:'fixture-owner',storage:'RAILWAY_VOLUME',availability:'AVAILABLE',created_at:'2026-10-08',download_url:'/api/files/fixture-file/download'}],tasks=[];
 await page.route('https://zar.invalid/**',async route=>{const url=new URL(route.request().url()),path=url.pathname;
  if(path.startsWith('/static/'))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync('app'+path,'utf8')});
  if(path==='/api/files')return route.fulfill({json:{ok:true,files:files.filter(f=>!url.searchParams.get('q')||f.name.toLowerCase().includes(url.searchParams.get('q').toLowerCase())),recovery:{storage:{storage:'RAILWAY_VOLUME'},recovered:1,missing_binaries:0}}});
  if(path==='/api/files/upload'){writes.push('upload');files.push({id:'fixture-upload',name:'uploaded.txt',size:12,mime:'text/plain',category:'documentos',owner_id:'fixture-owner',storage:'RAILWAY_VOLUME',availability:'AVAILABLE',download_url:'/api/files/fixture-upload/download'});return route.fulfill({json:{ok:true,files:[files.at(-1)]}});}
  if(path==='/api/semantic/tasks'&&route.request().method()==='POST'){tasks=[{id:'fixture-task',goal:'Investiga ayudas, haz un informe y envíaselo a Belloso',status:'PLANNED',subtasks:[{kind:'RESEARCH',status:'PLANNED'}],outputs:{},created_at:'2026-10-08'}];return route.fulfill({json:{ok:true,task:tasks[0]}});}
  if(path==='/api/semantic/tasks')return route.fulfill({json:{ok:true,csrf:'fixture-csrf',tasks}});
  if(path==='/api/semantic/tasks/fixture-task/run'){writes.push('run');tasks[0]={...tasks[0],status:'WAITING',subtasks:[{kind:'SEND_EMAIL',status:'WAITING',error:'Revisar'}],outputs:{DRAFT_EMAIL:{to:'fixture@example.test',subject:'Informe',body:'Adjunto informe fixture',cc:'',bcc:'',artifact_ids:['fixture-file']}}};return route.fulfill({json:{ok:true,task:tasks[0]}});}
  return route.fulfill({contentType:'text/html',body:`<div id="panelBody"><div class="zarFileToolbar"><input id="fileSearch"><button>Subir</button></div><div id="zarFileStats"></div><div id="zarFileList"></div></div><script src="/static/zar-ui.js"></script><script src="/static/file-memory.js"></script><script>window.body=document.getElementById('panelBody');window.zarFileCategory='';window.formatBytes=n=>n+' B';window.zarPanelEnhanced=()=>{};window.openPanel=()=>{};window.previewFile=()=>{};window.loadZarFiles=()=>{throw Error('Legacy function must be replaced after parsing')};</script><script src="/static/semantic-tasks.js"></script>`});
 });
 await page.goto('https://zar.invalid/');await page.evaluate(()=>loadZarFiles());await page.getByText('Informe fixture.pdf',{exact:true}).waitFor();assert.match(await page.locator('#zarFileStats').innerText(),/1 archivos/);
 for(const action of ['Preview','Renombrar','Mover','Compartir','Eliminar'])assert.equal(await page.getByRole('button',{name:action,exact:true}).count(),1);
 await page.locator('input[data-explorer-upload]').setInputFiles({name:'uploaded.txt',mimeType:'text/plain',buffer:Buffer.from('fixture data')});await page.getByText('uploaded.txt',{exact:true}).waitFor();assert.match(await page.locator('#zarFileStats').innerText(),/2 archivos/);
 await page.locator('#fileSearch').fill('Informe');await page.locator('#fileSearch').press('Enter');await page.waitForFunction(()=>document.getElementById('zarFileStats').textContent.includes('1 archivos'));
 await page.getByRole('button',{name:'Tareas e informes'}).click();await page.locator('#zarSemanticForm textarea').fill('Investiga ayudas, haz un informe y envíaselo a Belloso');await page.locator('#zarSemanticForm button').click();await page.getByText('fixture@example.test',{exact:false}).waitFor();assert.match(await page.locator('#zarSemanticTasks').innerText(),/WAITING/);
 const before=writes.length;await page.getByRole('button',{name:'Revisar y enviar',exact:true}).click();await page.locator('[data-zar-cancel]').click();await page.waitForTimeout(50);assert.equal(writes.length,before,'Cancel must not send');assert.deepEqual(errors,[]);console.log('PASS focused files/tasks UI '+width);await page.close();
 }}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
