const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.ZAR_TEST_BROWSER,args:['--autoplay-policy=no-user-gesture-required','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try{for(const [width,height] of [[390,844],[393,852],[412,915],[1440,900]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[],projects=new Map();page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async r=>{const p=new URL(r.request().url()).pathname;
  if(p==='/')return r.fulfill({contentType:'text/html',body:fs.readFileSync('app/templates/index.html')});
  if(p.startsWith('/static/')&&fs.existsSync('app'+p))return r.fulfill({contentType:p.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync('app'+p)});
  if(p==='/api/studio/music/projects')return r.fulfill({json:{ok:true,csrf:'fixture',projects:[...projects.values()]}});
  if(p.startsWith('/api/studio/music/projects/')){const id=p.split('/').pop();if(r.request().method()==='PUT'){projects.set(id,r.request().postDataJSON());return r.fulfill({json:{ok:true}});}return r.fulfill({json:{ok:true,project:projects.get(id)}});}
  return r.fulfill({json:{ok:true,csrf:'fixture',tasks:[],projects:[],files:[],companies:{},agents:[],events:[],skills:[],connectors:{},identity_center:{google:{},integrations:[],human_actions:[],plans:[],onboarding:[],capabilities:{}},view:{}}});
 });
 await page.goto('https://zar.test/');await page.waitForFunction(()=>window.ZarDAW&&window.WorkspaceTabsManager);await page.evaluate(()=>WorkspaceTabsManager.open('studio'));
 const f=page.frameLocator('iframe[title="ZAR Studio"]');await f.getByRole('button',{name:'🎧 AUDIO',exact:true}).click();await f.locator('.zarDAW [data-status]').waitFor();
 await f.getByRole('button',{name:'ZAR Producer',exact:true}).click();await f.locator('[data-producer] button').click();await f.locator('.dawRack tbody tr').first().waitFor();assert.equal(await f.locator('.dawRack tbody tr').count(),6);
 const frame=page.frames().find(f=>f.url().includes('zar_workspace=studio'));const project=await frame.evaluate(()=>ZarDAW.project());assert.equal(project.tempo,140);assert.equal(project.key,'A');assert.equal(project.tracks[3].instrument,'Bass');assert(project.tracks.every(t=>t.notes.length>0));
 await f.getByRole('button',{name:'Kick paso 2',exact:true}).click();assert.equal(await f.getByRole('button',{name:'Kick paso 2',exact:true}).getAttribute('aria-pressed'),'true');
 await f.getByRole('button',{name:'Piano roll',exact:true}).click();await f.locator('[data-piano]').click({position:{x:200,y:300}});const count=(await frame.evaluate(()=>ZarDAW.project())).tracks[0].notes.length;await f.getByRole('button',{name:'Borrar selección',exact:true}).click();assert.equal((await frame.evaluate(()=>ZarDAW.project())).tracks[0].notes.length,count-1);
 await f.getByRole('button',{name:'Mixer',exact:true}).click();await f.locator('[data-fx-add]').first().selectOption('Delay');assert.equal(await f.locator('[data-fx-on]').count(),1);
 await f.getByRole('button',{name:'▶ Play',exact:true}).click();await page.waitForTimeout(350);assert(await frame.evaluate(()=>ZarDAW.engine.playing&&ZarDAW.engine.current()>0));await f.getByRole('button',{name:'Ⅱ Pausa',exact:true}).click();assert(await frame.evaluate(()=>!ZarDAW.engine.playing&&ZarDAW.engine.position>0));await f.getByRole('button',{name:'■ Stop',exact:true}).click();assert.equal(await frame.evaluate(()=>ZarDAW.engine.position),0);
 await f.getByRole('button',{name:'Guardar',exact:true}).click();await f.locator('[data-status]').filter({hasText:'Proyecto guardado'}).waitFor();assert(projects.size>0);const saved=[...projects.values()][0];await frame.evaluate(p=>ZarDAW.load(p),saved);assert.equal((await frame.evaluate(()=>ZarDAW.project())).tracks[0].notes.length,saved.tracks[0].notes.length);
 const result=await frame.evaluate(async()=>{const p=ZarDAW.project();p.bars=4;const buffer=await ZarDAW.engine.offline(p);let peak=0,energy=0;for(const v of buffer.getChannelData(0)){peak=Math.max(peak,Math.abs(v));energy+=v*v;}return {duration:buffer.duration,sampleRate:buffer.sampleRate,channels:buffer.numberOfChannels,peak,energy,wav:Array.from(new Uint8Array(await ZarMusic.wav(buffer).arrayBuffer())),midi:Array.from(new Uint8Array(await ZarMusic.midi(p).arrayBuffer()))};});
 assert(result.duration>6&&result.duration<9);assert.equal(result.sampleRate,44100);assert.equal(result.channels,2);assert(result.peak>0&&result.energy>0);assert.equal(Buffer.from(result.wav).subarray(0,4).toString(),'RIFF');assert.equal(Buffer.from(result.midi).subarray(0,4).toString(),'MThd');
 fs.mkdirSync('artifacts/3327',{recursive:true});if(width===1440){
  fs.writeFileSync('artifacts/3327/trap-Aminor-140.wav',Buffer.from(result.wav));await f.getByRole('button',{name:'Arranger',exact:true}).click();const chooserPromise=page.waitForEvent('filechooser');await f.getByRole('button',{name:'Importar audio',exact:true}).click();await (await chooserPromise).setFiles(path.resolve('artifacts/3327/trap-Aminor-140.wav'));await f.locator('[data-status]').filter({hasText:'Audio importado'}).waitFor();assert.equal((await frame.evaluate(()=>ZarDAW.project())).tracks.filter(t=>t.instrument==='Audio').length,1);
  await f.locator('[name=clipGain]').fill('0.5');await f.locator('[name=clipGain]').dispatchEvent('change');assert.equal((await frame.evaluate(()=>ZarDAW.project())).tracks.at(-1).clips[0].gain,.5);
  await page.context().grantPermissions(['microphone']);await f.getByRole('button',{name:'● Grabar',exact:true}).click();await page.waitForTimeout(650);await f.getByRole('button',{name:'■ Terminar toma',exact:true}).click();await frame.waitForFunction(()=>ZarDAW.project().tracks.filter(t=>t.instrument==='Audio').reduce((n,t)=>n+t.clips.length,0)===2);
 }
 assert(await frame.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow');assert.deepEqual(errors,[]);console.log('PASS DAW, editable notes, FX, transport, persistence, WAV, MIDI '+width+'x'+height);await page.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
